-- Stage 8B: Seed core distribution rules for existing Registry assets

INSERT OR IGNORE INTO rules (
  rule_id, name, priority,
  match_object_type, match_program_family, match_commercial_role, match_capability_type, match_status
) VALUES
('RULE-OPEN-SERIES-HUB',
 'Open Series Hub Distribution',
 10,
 'COMPETITION-SERIES-HUB',
 'OPEN_SERIES',
 'SELLABLE',
 'SPONSORSHIP',
 'active'),

('RULE-OPEN-SERIES-DISTANCE',
 'Open Series Distance Distribution',
 20,
 'COMPETITION-DISTANCE-SERIES',
 'OPEN_SERIES',
 'SELLABLE',
 'SPONSORSHIP',
 'active'),

('RULE-OPEN-SERIES-EVENT',
 'Open Series Event Distribution',
 30,
 'COMPETITION-EVENT',
 'OPEN_SERIES',
 'PARTICIPATION',
 'PARTICIPATION',
 'active'),

('RULE-INSTRUCTOR-GROWTH-FUND',
 'Instructor Growth Fund Distribution',
 10,
 'FUNDRAISING-ASSET',
 'INSTRUCTOR_GROWTH_FUND',
 'SELLABLE',
 'FUNDRAISING',
 'active'),

('RULE-PARTNER-NETWORK',
 'Partner Network Distribution',
 20,
 'PARTNER-NETWORK',
 'PARTNER_NETWORK',
 'SELLABLE',
 'SPONSORSHIP',
 'active'),

('RULE-ATHLETE-ASSET',
 'Athlete Asset Distribution',
 20,
 'ATHLETE-ASSET',
 'ATHLETE_PROPERTY',
 'SELLABLE',
 'SPONSORSHIP',
 'active'),

('RULE-NWANA-SPORT',
 'NWANA Sport Distribution',
 20,
 'SPORT-ASSET',
 'NWANA_SPORT',
 'SELLABLE',
 'SPONSORSHIP',
 'active');


INSERT OR IGNORE INTO rule_audiences (
  audience_id, rule_id, audience_type
) VALUES

('AUD-SERIES-HUB-PARTICIPANTS', 'RULE-OPEN-SERIES-HUB', 'PARTICIPANTS'),
('AUD-SERIES-HUB-SPONSORS', 'RULE-OPEN-SERIES-HUB', 'SPONSORS'),
('AUD-SERIES-HUB-MEDIA', 'RULE-OPEN-SERIES-HUB', 'MEDIA'),
('AUD-SERIES-HUB-PARTNERS', 'RULE-OPEN-SERIES-HUB', 'PARTNERS'),

('AUD-SERIES-DIST-PARTICIPANTS', 'RULE-OPEN-SERIES-DISTANCE', 'PARTICIPANTS'),
('AUD-SERIES-DIST-SPONSORS', 'RULE-OPEN-SERIES-DISTANCE', 'SPONSORS'),
('AUD-SERIES-DIST-MEDIA', 'RULE-OPEN-SERIES-DISTANCE', 'MEDIA'),

('AUD-SERIES-EVENT-PARTICIPANTS', 'RULE-OPEN-SERIES-EVENT', 'PARTICIPANTS'),
('AUD-SERIES-EVENT-MEDIA', 'RULE-OPEN-SERIES-EVENT', 'MEDIA'),

('AUD-FUND-DONORS', 'RULE-INSTRUCTOR-GROWTH-FUND', 'DONORS'),
('AUD-FUND-SPONSORS', 'RULE-INSTRUCTOR-GROWTH-FUND', 'SPONSORS'),
('AUD-FUND-EMPLOYERS', 'RULE-INSTRUCTOR-GROWTH-FUND', 'EMPLOYERS'),
('AUD-FUND-MEDIA', 'RULE-INSTRUCTOR-GROWTH-FUND', 'MEDIA'),

('AUD-PARTNER-NETWORK-PARTNERS', 'RULE-PARTNER-NETWORK', 'PARTNERS'),
('AUD-PARTNER-NETWORK-SPONSORS', 'RULE-PARTNER-NETWORK', 'SPONSORS'),
('AUD-PARTNER-NETWORK-MEDIA', 'RULE-PARTNER-NETWORK', 'MEDIA'),

('AUD-ATHLETE-SPONSORS', 'RULE-ATHLETE-ASSET', 'SPONSORS'),
('AUD-ATHLETE-MEDIA', 'RULE-ATHLETE-ASSET', 'MEDIA'),
('AUD-ATHLETE-SPORT-PARTNERS', 'RULE-ATHLETE-ASSET', 'SPORT_PARTNERS'),

('AUD-SPORT-SPONSORS', 'RULE-NWANA-SPORT', 'SPONSORS'),
('AUD-SPORT-MEDIA', 'RULE-NWANA-SPORT', 'MEDIA'),
('AUD-SPORT-PARTNERS', 'RULE-NWANA-SPORT', 'PARTNERS');


INSERT OR IGNORE INTO rule_actions (
  action_id, rule_id, audience_id,
  action_type, channel, destination,
  execution_mode, priority
) VALUES

('ACT-SERIES-HUB-FB', 'RULE-OPEN-SERIES-HUB', 'AUD-SERIES-HUB-PARTICIPANTS',
 'SOCIAL_POST', 'FACEBOOK', 'NWANA', 'MANUAL_LAST_MILE', 10),

('ACT-SERIES-HUB-IG', 'RULE-OPEN-SERIES-HUB', 'AUD-SERIES-HUB-PARTICIPANTS',
 'SOCIAL_POST', 'INSTAGRAM', 'NWANA_OFFICIAL', 'MANUAL_LAST_MILE', 10),

('ACT-SERIES-HUB-LINKEDIN', 'RULE-OPEN-SERIES-HUB', 'AUD-SERIES-HUB-PARTICIPANTS',
 'SOCIAL_POST', 'LINKEDIN', 'NWANA_PAGE', 'APPROVAL_REQUIRED', 20),

('ACT-SERIES-HUB-EMAIL', 'RULE-OPEN-SERIES-HUB', 'AUD-SERIES-HUB-PARTICIPANTS',
 'EMAIL_CAMPAIGN', 'RUNSIGNUP_EMAIL', 'SERIES_PARTICIPANTS', 'NOT_CONNECTED', 20),

('ACT-SERIES-HUB-GOOGLE-ADS', 'RULE-OPEN-SERIES-HUB', 'AUD-SERIES-HUB-PARTICIPANTS',
 'GOOGLE_ADS_CAMPAIGN', 'GOOGLE_ADS_GRANT', 'OPEN_SERIES', 'APPROVAL_REQUIRED', 20),

('ACT-SERIES-HUB-SELLERS', 'RULE-OPEN-SERIES-HUB', 'AUD-SERIES-HUB-SPONSORS',
 'SELLER_OUTREACH', 'SELLER_NETWORK', 'NWANA_SELLERS', 'NOT_CONNECTED', 10),

('ACT-SERIES-HUB-SEAT-THEORY', 'RULE-OPEN-SERIES-HUB', 'AUD-SERIES-HUB-SPONSORS',
 'SPONSORSHIP_MARKETPLACE', 'SEAT_THEORY', 'OPEN_SERIES', 'NOT_CONNECTED', 20),

('ACT-SERIES-HUB-ZUBIE-FIVE', 'RULE-OPEN-SERIES-HUB', 'AUD-SERIES-HUB-SPONSORS',
 'SPONSORSHIP_MARKETPLACE', 'ZUBIE_FIVE', 'OPEN_SERIES', 'NOT_CONNECTED', 20),

('ACT-SERIES-HUB-PRESS', 'RULE-OPEN-SERIES-HUB', 'AUD-SERIES-HUB-MEDIA',
 'PRESS_OUTREACH', 'MEDIA', 'SPORT_AND_HEALTH_MEDIA', 'NOT_CONNECTED', 30),

('ACT-SERIES-HUB-PARTNERS', 'RULE-OPEN-SERIES-HUB', 'AUD-SERIES-HUB-PARTNERS',
 'PARTNER_OUTREACH', 'PARTNER_NETWORK', 'SPORT_WELLNESS_EMPLOYER_COMMUNITY', 'NOT_CONNECTED', 30),


('ACT-SERIES-DIST-FB', 'RULE-OPEN-SERIES-DISTANCE', 'AUD-SERIES-DIST-PARTICIPANTS',
 'SOCIAL_POST', 'FACEBOOK', 'NWANA', 'MANUAL_LAST_MILE', 20),

('ACT-SERIES-DIST-IG', 'RULE-OPEN-SERIES-DISTANCE', 'AUD-SERIES-DIST-PARTICIPANTS',
 'SOCIAL_POST', 'INSTAGRAM', 'NWANA_OFFICIAL', 'MANUAL_LAST_MILE', 20),

('ACT-SERIES-DIST-EMAIL', 'RULE-OPEN-SERIES-DISTANCE', 'AUD-SERIES-DIST-PARTICIPANTS',
 'EMAIL_CAMPAIGN', 'RUNSIGNUP_EMAIL', 'DISTANCE_SERIES_AUDIENCE', 'NOT_CONNECTED', 20),

('ACT-SERIES-DIST-SELLERS', 'RULE-OPEN-SERIES-DISTANCE', 'AUD-SERIES-DIST-SPONSORS',
 'SELLER_OUTREACH', 'SELLER_NETWORK', 'NWANA_SELLERS', 'NOT_CONNECTED', 20),

('ACT-SERIES-DIST-PRESS', 'RULE-OPEN-SERIES-DISTANCE', 'AUD-SERIES-DIST-MEDIA',
 'PRESS_OUTREACH', 'MEDIA', 'SPORT_MEDIA', 'NOT_CONNECTED', 30),


('ACT-SERIES-EVENT-FB', 'RULE-OPEN-SERIES-EVENT', 'AUD-SERIES-EVENT-PARTICIPANTS',
 'SOCIAL_POST', 'FACEBOOK', 'NWANA', 'MANUAL_LAST_MILE', 20),

('ACT-SERIES-EVENT-IG', 'RULE-OPEN-SERIES-EVENT', 'AUD-SERIES-EVENT-PARTICIPANTS',
 'SOCIAL_POST', 'INSTAGRAM', 'NWANA_OFFICIAL', 'MANUAL_LAST_MILE', 20),

('ACT-SERIES-EVENT-EMAIL', 'RULE-OPEN-SERIES-EVENT', 'AUD-SERIES-EVENT-PARTICIPANTS',
 'EMAIL_CAMPAIGN', 'RUNSIGNUP_EMAIL', 'EVENT_AUDIENCE', 'NOT_CONNECTED', 20),

('ACT-SERIES-EVENT-PRESS', 'RULE-OPEN-SERIES-EVENT', 'AUD-SERIES-EVENT-MEDIA',
 'PRESS_OUTREACH', 'MEDIA', 'LOCAL_AND_SPORT_MEDIA', 'NOT_CONNECTED', 30),


('ACT-FUND-DONOR-EMAIL', 'RULE-INSTRUCTOR-GROWTH-FUND', 'AUD-FUND-DONORS',
 'FUNDRAISING_OUTREACH', 'EMAIL', 'DONOR_AUDIENCE', 'NOT_CONNECTED', 10),

('ACT-FUND-FB', 'RULE-INSTRUCTOR-GROWTH-FUND', 'AUD-FUND-DONORS',
 'SOCIAL_POST', 'FACEBOOK', 'NWANA', 'MANUAL_LAST_MILE', 20),

('ACT-FUND-IG', 'RULE-INSTRUCTOR-GROWTH-FUND', 'AUD-FUND-DONORS',
 'SOCIAL_POST', 'INSTAGRAM', 'NWANA_OFFICIAL', 'MANUAL_LAST_MILE', 20),

('ACT-FUND-SELLERS', 'RULE-INSTRUCTOR-GROWTH-FUND', 'AUD-FUND-SPONSORS',
 'SELLER_OUTREACH', 'SELLER_NETWORK', 'NWANA_SELLERS', 'NOT_CONNECTED', 10),

('ACT-FUND-SEAT-THEORY', 'RULE-INSTRUCTOR-GROWTH-FUND', 'AUD-FUND-SPONSORS',
 'SPONSORSHIP_MARKETPLACE', 'SEAT_THEORY', 'INSTRUCTOR_GROWTH_FUND', 'NOT_CONNECTED', 20),

('ACT-FUND-ZUBIE-FIVE', 'RULE-INSTRUCTOR-GROWTH-FUND', 'AUD-FUND-SPONSORS',
 'SPONSORSHIP_MARKETPLACE', 'ZUBIE_FIVE', 'INSTRUCTOR_GROWTH_FUND', 'NOT_CONNECTED', 20),

('ACT-FUND-EMPLOYER-MATCH', 'RULE-INSTRUCTOR-GROWTH-FUND', 'AUD-FUND-EMPLOYERS',
 'CORPORATE_GIVING_OUTREACH', 'EMPLOYER_MATCHING', 'MATCHING_GIFT_EMPLOYERS', 'NOT_CONNECTED', 20),

('ACT-FUND-PRESS', 'RULE-INSTRUCTOR-GROWTH-FUND', 'AUD-FUND-MEDIA',
 'PRESS_OUTREACH', 'MEDIA', 'HEALTH_EDUCATION_NONPROFIT_MEDIA', 'NOT_CONNECTED', 30),


('ACT-PARTNER-OUTREACH', 'RULE-PARTNER-NETWORK', 'AUD-PARTNER-NETWORK-PARTNERS',
 'PARTNER_OUTREACH', 'PARTNER_NETWORK', 'ALL_PARTNER_TYPES', 'NOT_CONNECTED', 10),

('ACT-PARTNER-SPONSOR-SELLERS', 'RULE-PARTNER-NETWORK', 'AUD-PARTNER-NETWORK-SPONSORS',
 'SELLER_OUTREACH', 'SELLER_NETWORK', 'NWANA_SELLERS', 'NOT_CONNECTED', 20),

('ACT-PARTNER-PRESS', 'RULE-PARTNER-NETWORK', 'AUD-PARTNER-NETWORK-MEDIA',
 'PRESS_OUTREACH', 'MEDIA', 'BUSINESS_SPORT_NONPROFIT_MEDIA', 'NOT_CONNECTED', 30),


('ACT-ATHLETE-SELLERS', 'RULE-ATHLETE-ASSET', 'AUD-ATHLETE-SPONSORS',
 'SELLER_OUTREACH', 'SELLER_NETWORK', 'NWANA_SELLERS', 'NOT_CONNECTED', 10),

('ACT-ATHLETE-SEAT-THEORY', 'RULE-ATHLETE-ASSET', 'AUD-ATHLETE-SPONSORS',
 'SPONSORSHIP_MARKETPLACE', 'SEAT_THEORY', 'ATHLETE_ASSET', 'NOT_CONNECTED', 20),

('ACT-ATHLETE-ZUBIE-FIVE', 'RULE-ATHLETE-ASSET', 'AUD-ATHLETE-SPONSORS',
 'SPONSORSHIP_MARKETPLACE', 'ZUBIE_FIVE', 'ATHLETE_ASSET', 'NOT_CONNECTED', 20),

('ACT-ATHLETE-PRESS', 'RULE-ATHLETE-ASSET', 'AUD-ATHLETE-MEDIA',
 'PRESS_OUTREACH', 'MEDIA', 'SPORT_MEDIA', 'NOT_CONNECTED', 20),

('ACT-ATHLETE-PARTNERS', 'RULE-ATHLETE-ASSET', 'AUD-ATHLETE-SPORT-PARTNERS',
 'PARTNER_OUTREACH', 'PARTNER_NETWORK', 'SPORT_EQUIPMENT_MEDIA', 'NOT_CONNECTED', 30),


('ACT-SPORT-SELLERS', 'RULE-NWANA-SPORT', 'AUD-SPORT-SPONSORS',
 'SELLER_OUTREACH', 'SELLER_NETWORK', 'NWANA_SELLERS', 'NOT_CONNECTED', 10),

('ACT-SPORT-SEAT-THEORY', 'RULE-NWANA-SPORT', 'AUD-SPORT-SPONSORS',
 'SPONSORSHIP_MARKETPLACE', 'SEAT_THEORY', 'NWANA_SPORT', 'NOT_CONNECTED', 20),

('ACT-SPORT-ZUBIE-FIVE', 'RULE-NWANA-SPORT', 'AUD-SPORT-SPONSORS',
 'SPONSORSHIP_MARKETPLACE', 'ZUBIE_FIVE', 'NWANA_SPORT', 'NOT_CONNECTED', 20),

('ACT-SPORT-PRESS', 'RULE-NWANA-SPORT', 'AUD-SPORT-MEDIA',
 'PRESS_OUTREACH', 'MEDIA', 'SPORT_MEDIA', 'NOT_CONNECTED', 20),

('ACT-SPORT-PARTNERS', 'RULE-NWANA-SPORT', 'AUD-SPORT-PARTNERS',
 'PARTNER_OUTREACH', 'PARTNER_NETWORK', 'SPORT_HEALTH_WELLNESS', 'NOT_CONNECTED', 30);
