-- Add reviewable business instructions to the 10 Series 2026 hub actions.
-- Draft planning only; no send or publication.

UPDATE rule_actions SET metadata='{"purpose":"Promote Series 2026 to Nordic walking participants on Facebook","deliverable":"Facebook post for the NWANA page","call_to_action":"Visit the Series hub and choose a distance","content_scope":"SERIES_PROMOTION"}', updated_at=CURRENT_TIMESTAMP WHERE action_id='ACT-SERIES-HUB-FB';
UPDATE rule_actions SET metadata='{"purpose":"Promote Series 2026 to Nordic walking participants on Instagram","deliverable":"Instagram post for NWANA Official","call_to_action":"Visit the Series hub and choose a distance","content_scope":"SERIES_PROMOTION"}', updated_at=CURRENT_TIMESTAMP WHERE action_id='ACT-SERIES-HUB-IG';
UPDATE rule_actions SET metadata='{"purpose":"Present Series 2026 as a participation and organizational opportunity on LinkedIn","deliverable":"LinkedIn post for the NWANA page","call_to_action":"Visit the Series hub or contact NWANA","content_scope":"SERIES_PROMOTION"}', updated_at=CURRENT_TIMESTAMP WHERE action_id='ACT-SERIES-HUB-LINKEDIN';
UPDATE rule_actions SET metadata='{"purpose":"Inform existing Series participants about the Series hub and the next participation opportunity","deliverable":"RunSignup email draft for Series participants","call_to_action":"Visit the Series hub and choose the next distance","content_scope":"PARTICIPANT_FOLLOW_UP"}', updated_at=CURRENT_TIMESTAMP WHERE action_id='ACT-SERIES-HUB-EMAIL';
UPDATE rule_actions SET metadata='{"purpose":"Attract people searching for Nordic walking competitions to Series 2026","deliverable":"Google Ad Grant campaign draft","call_to_action":"Visit the Series hub and choose a distance","content_scope":"SERIES_ACQUISITION"}', updated_at=CURRENT_TIMESTAMP WHERE action_id='ACT-SERIES-HUB-GOOGLE-ADS';
UPDATE rule_actions SET metadata='{"purpose":"Give NWANA sponsorship sellers a clear Series 2026 asset to present","deliverable":"Seller outreach brief for Series 2026","call_to_action":"Open a sponsorship conversation with NWANA","content_scope":"SPONSORSHIP_SALES"}', updated_at=CURRENT_TIMESTAMP WHERE action_id='ACT-SERIES-HUB-SELLERS';
UPDATE rule_actions SET metadata='{"purpose":"Prepare Series 2026 for sponsorship marketplace visibility","deliverable":"Seat Theory listing draft","call_to_action":"Request a sponsor introduction or sponsorship conversation","content_scope":"SPONSORSHIP_MARKETPLACE"}', updated_at=CURRENT_TIMESTAMP WHERE action_id='ACT-SERIES-HUB-SEAT-THEORY';
UPDATE rule_actions SET metadata='{"purpose":"Prepare Series 2026 for sponsorship marketplace visibility","deliverable":"Zubie Five listing draft","call_to_action":"Request a sponsor introduction or sponsorship conversation","content_scope":"SPONSORSHIP_MARKETPLACE"}', updated_at=CURRENT_TIMESTAMP WHERE action_id='ACT-SERIES-HUB-ZUBIE-FIVE';
UPDATE rule_actions SET metadata='{"purpose":"Pitch Series 2026 to sports and health media","deliverable":"Press pitch draft","call_to_action":"Cover Series 2026 or contact NWANA for information","content_scope":"MEDIA_OUTREACH"}', updated_at=CURRENT_TIMESTAMP WHERE action_id='ACT-SERIES-HUB-PRESS';
UPDATE rule_actions SET metadata='{"purpose":"Invite sport, wellness, employer, and community partners to support or distribute Series 2026","deliverable":"Partner outreach brief","call_to_action":"Discuss partnership, audience distribution, hosting, or support","content_scope":"PARTNER_OUTREACH"}', updated_at=CURRENT_TIMESTAMP WHERE action_id='ACT-SERIES-HUB-PARTNERS';
