-- Migration 0035: seed the verified media registry.
--
-- Generated 2026-09-27 from ~/workspace/media/free-pr-entry-points-catalog.md
-- plus the verified free press-platform research (PRLog, PR.com, OpenPR,
-- PRFree, 1888PressRelease, FreePressRelease.io, CircleActs).
--
-- No URLs were invented: every URL comes from the catalog or is NULL
-- pending manual confirmation. Every row keeps its verification_level:
-- 'opened' = page opened and read 2026-09-27; 'search_verified' / 'third_party'
-- require manual browser verification before first use.
-- All contacts are consent_class='RESEARCHED_COLD': individual targeted
-- outreach only, never Email V2 bulk (architectural boundary).
--
-- Re-runnable: all inserts are INSERT OR IGNORE on UNIQUE keys.

-- Seed: media distribution system registry (research 2026-09-27).
-- Sources: ~/workspace/media/free-pr-entry-points-catalog.md + verified press-platform research.
-- verification_level: opened | search_verified | third_party. Only 'opened' rows are cleared for immediate use.

INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('wfts-tv-tampa-bay-28', 'WFTS-TV / Tampa Bay 28 — Newsroom', 'local_media', 'local', 'Florida', '["local", "florida"]', 'https://www.tampabay28.com/about/contact-us', 'opened', 'Tampa Bay; также контакты конкретных журналистов на staff page');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('central-florida-public-media-orlando-npr-member', 'Central Florida Public Media (Orlando, NPR member)', 'local_media', 'local', 'Florida', '["local", "florida"]', 'https://www.cfpublic.org/contact-us', 'opened', 'Центральная Флорида');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('news4jax-wjxt-jacksonville', 'News4JAX / WJXT (Jacksonville)', 'local_media', 'local', 'Florida', '["local", "florida"]', 'http://gmg-wjxt-prod.cdn.arcpublishing.com/contact/', 'search_verified', 'Перед использованием открыть страницу');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('wftv-9-investigates-orlando', 'WFTV 9 Investigates (Orlando)', 'local_media', 'local', 'Florida', '["local", "florida"]', 'https://docs.google.com/forms/d/e/1FAIpQLSfFdzBqzkJfQq_F8OArbMhlLwtUeiB2zV7k0OT7TnJskh8lQw/viewform?pli=1&usp=embed_facebook', 'search_verified', 'Investigative angle; не для обычных анонсов');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('wplg-local-10-miami', 'WPLG Local 10 (Miami)', 'local_media', 'local', 'Florida', '["local", "florida"]', 'http://www.local10.com/', 'search_verified', 'Investigative; официальную contact-страницу ещё не найден');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('fox-35-orlando-wofl', 'FOX 35 Orlando (WOFL)', 'local_media', 'local', 'Florida', '["local", "florida"]', 'https://www.fox35orlando.com/about', 'search_verified', 'Email newsroom из сниппета обрезан (`FOX35Tips@FOX…`) — не использовать без проверки');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('florida-times-union', 'Florida Times-Union — Opinion', 'local_media', 'local', 'Florida', '["local", "florida"]', 'https://www.jacksonville.com/story/opinion/2021/09/10/how-submit-letter-guest-column-florida-times-union-jacksonville/8272255002/', 'search_verified', 'Jacksonville-area ограничение');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('associated-press', 'Associated Press — Contact the Newsroom', 'national_media', 'national', 'US', '["national"]', 'https://www.ap.org/contact-us/contact-the-newsroom/', 'opened', 'Национальная значимость обязательна');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('new-york-times', 'New York Times — Tips', 'national_media', 'national', 'US', '["national"]', 'https://www.nytimes.com/tips', 'search_verified', 'Подтвердить live-открытием');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('washington-post', 'Washington Post — Anonymous tips', 'national_media', 'national', 'US', '["national"]', 'https://www.washingtonpost.com/anonymous-news-tips/', 'third_party', 'URL из справочного источника — проверить live');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('abc-news', 'ABC News — Share a tip', 'national_media', 'national', 'US', '["national"]', 'https://abcnews.go.com/US/tip-share-abc-news/story?id=61304290', 'search_verified', '—');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('usa-today-forum-opinion', 'USA TODAY Forum (opinion)', 'national_media', 'national', 'US', '["national"]', 'https://www.beaconjournal.com/story/opinion/2025/01/26/usa-today-forum-share-your-voice/77884398007/', 'search_verified', 'Статья — republication Gannett, проверить актуальность адреса');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('wfts-tv-tampa-bay-28-2', 'WFTS-TV Tampa Bay 28 — Newsroom', 'tv_radio', 'local', '', '["tv", "radio"]', 'https://www.tampabay28.com/about/contact-us', 'opened', '—');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('wftv-9-investigates', 'WFTV 9 Investigates', 'tv_radio', 'local', '', '["tv", "radio"]', 'https://docs.google.com/forms/d/e/1FAIpQLSfFdzBqzkJfQq_F8OArbMhlLwtUeiB2zV7k0OT7TnJskh8lQw/viewform?pli=1&usp=embed_facebook', 'search_verified', 'Investigative');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('wplg-local-10', 'WPLG Local 10', 'tv_radio', 'local', '', '["tv", "radio"]', 'http://www.local10.com/', 'search_verified', '—');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('fox-35-orlando', 'FOX 35 Orlando', 'tv_radio', 'local', '', '["tv", "radio"]', 'https://www.fox35orlando.com/about', 'search_verified', '—');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('central-florida-public-media-npr', 'Central Florida Public Media (NPR)', 'tv_radio', 'local', '', '["tv", "radio"]', 'https://www.cfpublic.org/contact-us', 'opened', '—');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('npr-health-freelance-guide', 'NPR Health freelance guide', 'tv_radio', 'local', '', '["tv", "radio"]', 'https://healthjournalism.org/freelancers/freelance-market-guide/npr-freelance-market-guide/', 'third_party', 'Только health angle, freelance-формат; гайд сторонний — подтвердить на NPR');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('tampa-bay-times', 'Tampa Bay Times — Submit a letter', 'newspaper_magazine', 'local', '', '["newspaper", "magazine"]', 'https://tampabaytimes-tampa-bay-times.cdn.zephr.com/opinion/submit-letter/', 'search_verified', 'Только letters; не news tips');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('usa-today-forum', 'USA TODAY Forum', 'newspaper_magazine', 'local', '', '["newspaper", "magazine"]', 'https://www.beaconjournal.com/story/opinion/2025/01/26/usa-today-forum-share-your-voice/77884398007/', 'search_verified', 'Проверить актуальность');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('outside', 'Outside — pitch contacts', 'newspaper_magazine', 'local', '', '["newspaper", "magazine"]', 'https://www.outsideonline.com/magazine/contact-us/how-to-pitch-freelance-outside-magazine/?scope=anon', 'search_verified', 'Freelance/editorial bar высокий');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('chronicle-of-philanthropy', 'Chronicle of Philanthropy — Opinion', 'newspaper_magazine', 'local', '', '["newspaper", "magazine"]', 'https://www.philanthropy.com/how-to-submit-an-opinion-piece/', 'search_verified', 'Exclusivity required для opinion');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('nonprofit-quarterly', 'Nonprofit Quarterly — Submissions', 'newspaper_magazine', 'local', '', '["newspaper", "magazine"]', 'https://nonprofitquarterly.org/submissions/', 'opened', 'No press releases, no self-promotion; оригинал + эксклюзивность');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('next-avenue-pbs-50-audience', 'Next Avenue (PBS 50+ audience)', 'health_aging', 'local', '', '["health", "aging", "50plus"]', 'https://healthjournalism.org/freelancers/freelance-market-guide/next-avenue-freelance-market-guide/', 'third_party', '50+ аудитория; гайд сторонний');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('npr-shots-goats-soda', 'NPR Shots / Goats & Soda', 'health_aging', 'local', '', '["health", "aging", "50plus"]', 'https://healthjournalism.org/freelancers/freelance-market-guide/npr-freelance-market-guide/', 'third_party', 'Только health angle; подтвердить на NPR');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('beacon-senior-news', 'Beacon Senior News — Write for Us', 'health_aging', 'local', '', '["health", "aging", "50plus"]', 'https://coloradosprings.beaconseniornews.com/pages/write', 'search_verified', 'Регион Colorado Springs–Pueblo; только для релевантных историй');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('run247', 'RUN247 — News & Interviews', 'health_aging', 'local', '', '["health", "aging", "50plus"]', 'https://run247.com/work-with-us', 'search_verified', 'Off-road/trail фокус; news team не берёт gear/nutrition/commercial');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('wjxt-news4jax', 'WJXT News4JAX — Sports desk', 'sports', 'local', '', '["sports"]', 'http://gmg-wjxt-prod.cdn.arcpublishing.com/contact/', 'search_verified', 'Jacksonville/Florida спорт');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('runner-s-world', 'Runner''s World — News tips', 'sports', 'local', '', '["sports"]', NULL, 'third_party', 'НЕ использовать без подтверждения на hearst.com');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('sports-page', 'Sports Page — ideas', 'sports', 'local', '', '["sports"]', 'https://github.com/pem725/the-sports-page/blob/HEAD/tracking/contributor-pipeline.md', 'third_party', 'Только идеи с числом в центре; источник — чужой workflow, не официальный сайт издания');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('the-outdoor-journal', 'The Outdoor Journal — Contribute', 'running_outdoor', 'local', '', '["running", "endurance", "outdoor"]', 'https://www.outdoorjournal.com/contribute/', 'search_verified', 'Outdoor фокус');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('running-usa', 'Running USA — editorial', 'running_outdoor', 'local', '', '["running", "endurance", "outdoor"]', 'https://www.runningusa.org/about-us/running-usa-about/', 'search_verified', 'Press-release distribution — только member benefit (не бесплатно без членства)');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('usa-running-races', 'USA Running Races — listings', 'running_outdoor', 'local', '', '["running", "endurance", "outdoor"]', 'https://usarunningraces.com/wp-content/uploads/USARunningRacesMediaKit.pdf', 'search_verified', 'Premium — платный');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('ahotu', 'AHOTU — event listings', 'running_outdoor', 'local', '', '["running", "endurance", "outdoor"]', 'https://www.worldssportsgroup.com/news/ahotu-expands-coverage', 'search_verified', 'Календарь включает walking/Nordic walking; релевантен');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('inside-philanthropy', 'Inside Philanthropy — News', 'nonprofit_philanthropy', 'local', '', '["nonprofit", "philanthropy"]', 'https://www.insidephilanthropy.com/about/contact', 'search_verified', 'Philanthropy/nonprofit фокус');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('inside-philanthropy-2', 'Inside Philanthropy — Guest posts', 'nonprofit_philanthropy', 'local', '', '["nonprofit", "philanthropy"]', 'https://www.insidephilanthropy.com/about/guest-post-guidelines', 'search_verified', 'Только про конкретную nonprofit program обычно НЕ подходит — нужен sector angle');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('chronicle-newsroom', 'Chronicle newsroom', 'nonprofit_philanthropy', 'local', '', '["nonprofit", "philanthropy"]', 'https://philanthropy.com/contact-us/', 'search_verified', 'Национальная значимость');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('nonprofit-quarterly-2', 'Nonprofit Quarterly — Volunteer newswire writers', 'nonprofit_philanthropy', 'local', '', '["nonprofit", "philanthropy"]', 'https://nonprofitquarterly.org/join-the-npq-writers-cadre/', 'search_verified', 'Волонтёрская роль, требует регулярности');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('uf-news', 'UF News — Submit a Story', 'university', 'local', '', '["university"]', 'https://news.ufl.edu/submit-a-story/', 'search_verified', 'Только UF-connected work; события не продвигает');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('uf-at-work', 'UF at Work — Submit a Story', 'university', 'local', '', '["university"]', 'https://news.hr.ufl.edu/submit-a-story/', 'search_verified', 'Только UF faculty/staff');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('uf-phhp', 'UF PHHP — Submit a Story Idea', 'university', 'local', '', '["university"]', 'https://phhp.ufl.edu/news-and-events/submit-a-story-idea/', 'search_verified', 'Нужна реальная UF connection');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('university-of-miami', 'University of Miami — News contact', 'university', 'local', '', '["university"]', 'https://news.miami.edu/contact/', 'search_verified', 'Scope проверить; вероятно внутренняя');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('ucf-cecs', 'UCF CECS — Share Your News', 'university', 'local', '', '["university"]', 'https://www.cecs.ucf.edu/share-your-news/', 'search_verified', 'Только college-internal; ответ 5–7 business days');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('fsu-media-resources', 'FSU Media Resources', 'university', 'local', '', '["university"]', 'https://news.fsu.edu/for-journalists/media-resources/', 'search_verified', 'Для журналистских запросов К FSU, не для внешних питчей — исключён как точка входа');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('miami-community-newspapers', 'Miami Community Newspapers', 'community', 'local', '', '["community", "local"]', 'https://communitynewspapers.com', 'search_verified', 'Только Miami-Dade');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('patch', 'Patch — Neighbor Posts / Events', 'community', 'local', '', '["community", "local"]', 'https://patch.com', 'search_verified', 'Нужна локальная привязка (real local); бизнесы — только featured');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('newsbreak', 'NewsBreak', 'community', 'local', '', '["community", "local"]', NULL, 'third_party', 'Официальный creator route не найден; сторонний PR про бесплатный Spotlight для small business — не подтверждён как nonprofit route. Исключён.');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('axios-tampa-bay', 'Axios Tampa Bay', 'community', 'local', '', '["community", "local"]', NULL, 'third_party', 'Newsletter существует, но официальный pitch/tip contact не найден. Гэп.');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('podcastguests', 'PodcastGuests — Guest Match Service', 'podcast', 'local', '', '["podcast"]', 'https://podcastguests.com/guest-match-service/', 'opened', 'Ручной питч по каждому подкасту');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('the-morning-shakeout-running-newsletter-podcast', 'The Morning Shakeout (running newsletter + podcast)', 'podcast', 'local', '', '["podcast"]', 'https://themorningshakeout.com/about/', 'search_verified', 'Weekly running audience');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('eventbrite', 'Eventbrite', 'event_calendar', 'local', '', '["event", "calendar"]', 'https://www.eventbrite.com/organizer/pricing/', 'search_verified', 'Для платных событий — ticketing fees; `VERIFIED $0` только для free-attendee events');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('allevents', 'AllEvents', 'event_calendar', 'local', '', '["event", "calendar"]', 'https://allevents.in/pages/onboard', 'search_verified', '—');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('usa-running-races-2', 'USA Running Races', 'event_calendar', 'local', '', '["event", "calendar"]', 'https://usarunningraces.com/wp-content/uploads/USARunningRacesMediaKit.pdf', 'search_verified', 'Premium — платный');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('ahotu-2', 'AHOTU', 'event_calendar', 'local', '', '["event", "calendar"]', 'https://www.worldssportsgroup.com/news/ahotu-expands-coverage', 'search_verified', 'Включает walking/Nordic walking');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('run-asheville', 'Run Asheville — Submit Event', 'event_calendar', 'local', '', '["event", "calendar"]', 'https://runasheville.com:443/submit-event/', 'search_verified', 'Только Western North Carolina');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('indy-week-cityspark', 'INDY Week / CitySpark', 'event_calendar', 'local', '', '["event", "calendar"]', 'https://indyweek.com/wp-content/uploads/2025/11/How-to-Submit-an-Event-to-INDY-Calendar_CitySpark-Website.pdf', 'search_verified', 'География North Carolina');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('patch-community-calendar', 'Patch Community Calendar', 'event_calendar', 'local', '', '["event", "calendar"]', 'https://patch.com', 'search_verified', 'Локальная привязка');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('prlog', 'PRLog — submit', 'press_platform', 'national', '', '["press_release", "syndication"]', 'https://www.prlog.Org/pub/', 'search_verified', '—');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('prlog-2', 'PRLog — free account/submission', 'press_platform', 'national', '', '["press_release", "syndication"]', 'http://www.prlog.org/submit-free-press-release.html', 'search_verified', 'Только через форму после логина');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('haro-revival', 'HARO (revival)', 'press_platform', 'national', '', '["press_release", "syndication"]', NULL, 'third_party', 'URL не конструировать — найти официально');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('podcastguests-2', 'PodcastGuests — Guest Match', 'press_platform', 'national', '', '["press_release", "syndication"]', 'https://podcastguests.com/guest-match-service/', 'opened', '—');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('openpr-pr-com', 'OpenPR / PR.com', 'press_platform', 'national', '', '["press_release", "syndication"]', NULL, 'third_party', 'Только сторонние упоминания; без открытых official pricing/submission pages — не включать');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('circleacts', 'CircleActs', 'press_platform', 'national', '', '["press_release", "syndication"]', NULL, 'third_party', 'Не исследован — гэп');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('pr-com', 'PR.com', 'press_platform', 'national', '', '["press_release", "syndication"]', NULL, 'third_party', 'Free basic press-release submissions + company profile; links are paid.');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('openpr', 'OpenPR', 'press_platform', 'national', '', '["press_release", "syndication"]', NULL, 'third_party', 'One free press release every 30 days; paid credits beyond.');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('prfree', 'PRFree', 'press_platform', 'national', '', '["press_release", "syndication"]', NULL, 'third_party', 'Unlimited free submissions with links per comparison tables.');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('1888pressrelease', '1888PressRelease', 'press_platform', 'national', '', '["press_release", "syndication"]', NULL, 'third_party', 'Free submission/distribution to their network; paid upgrade optional.');
INSERT OR IGNORE INTO media_outlets (outlet_id, name, outlet_type, scope, geography, categories, website_url, verification_level, notes) VALUES ('freepressrelease-io', 'FreePressRelease.io', 'press_platform', 'national', '', '["press_release", "syndication"]', NULL, 'third_party', 'Free submission, no credit card.');

INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('wfts-tv-tampa-bay-28-newsroom-news-tip-pitch', 'wfts-tv-tampa-bay-28', 'WFTS-TV / Tampa Bay 28 — Newsroom', 'https://www.tampabay28.com/about/contact-us', '["news_tip", "pitch"]', 'email,phone', 'EXPECTED $0 — no fee shown', 'Tampa Bay; также контакты конкретных журналистов на staff page', 'opened', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('central-florida-public-media-orlando-npr-news-tip-pitch', 'central-florida-public-media-orlando-npr-member', 'Central Florida Public Media (Orlando, NPR member)', 'https://www.cfpublic.org/contact-us', '["news_tip", "pitch"]', 'email,phone', 'EXPECTED $0 — no fee shown', 'Центральная Флорида', 'opened', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('news4jax-wjxt-jacksonville-news-tip', 'news4jax-wjxt-jacksonville', 'News4JAX / WJXT (Jacksonville)', 'http://gmg-wjxt-prod.cdn.arcpublishing.com/contact/', '["news_tip"]', 'email,phone', 'EXPECTED $0 — no fee shown', 'Перед использованием открыть страницу', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('wftv-9-investigates-orlando-news-tip-pitch', 'wftv-9-investigates-orlando', 'WFTV 9 Investigates (Orlando)', 'https://docs.google.com/forms/d/e/1FAIpQLSfFdzBqzkJfQq_F8OArbMhlLwtUeiB2zV7k0OT7TnJskh8lQw/viewform?pli=1&usp=embed_facebook', '["news_tip", "pitch"]', 'web_form,email,phone', 'EXPECTED $0 — no fee shown', 'Investigative angle; не для обычных анонсов', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('wplg-local-10-miami-pitch', 'wplg-local-10-miami', 'WPLG Local 10 (Miami)', 'http://www.local10.com/', '["pitch"]', 'email', 'EXPECTED $0 — no fee shown', 'Investigative; официальную contact-страницу ещё не найден', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('fox-35-orlando-wofl-news-tip', 'fox-35-orlando-wofl', 'FOX 35 Orlando (WOFL)', 'https://www.fox35orlando.com/about', '["news_tip"]', 'phone', 'EXPECTED $0 — no fee shown', 'Email newsroom из сниппета обрезан (`FOX35Tips@FOX…`) — не использовать без проверки', 'search_verified', 'Call the desk; note date, person spoken to, and outcome in media_distributions.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('florida-times-union-opinion-guest-pitch-opinion', 'florida-times-union', 'Florida Times-Union — Opinion', 'https://www.jacksonville.com/story/opinion/2021/09/10/how-submit-letter-guest-column-florida-times-union-jacksonville/8272255002/', '["guest_pitch", "opinion"]', 'email', 'EXPECTED $0 — no fee shown', 'Jacksonville-area ограничение', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('associated-press-contact-the-newsroom-press-release-news-t', 'associated-press', 'Associated Press — Contact the Newsroom', 'https://www.ap.org/contact-us/contact-the-newsroom/', '["press_release", "news_tip"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Национальная значимость обязательна', 'opened', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('new-york-times-tips-news-tip', 'new-york-times', 'New York Times — Tips', 'https://www.nytimes.com/tips', '["news_tip"]', 'web_form', 'UNKNOWN', 'Подтвердить live-открытием', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('washington-post-anonymous-tips-news-tip', 'washington-post', 'Washington Post — Anonymous tips', 'https://www.washingtonpost.com/anonymous-news-tips/', '["news_tip"]', 'web_form', 'UNKNOWN', 'URL из справочного источника — проверить live', 'third_party', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('abc-news-share-a-tip-news-tip', 'abc-news', 'ABC News — Share a tip', 'https://abcnews.go.com/US/tip-share-abc-news/story?id=61304290', '["news_tip"]', 'web_form', 'UNKNOWN', '—', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('usa-today-forum-opinion-opinion', 'usa-today-forum-opinion', 'USA TODAY Forum (opinion)', 'https://www.beaconjournal.com/story/opinion/2025/01/26/usa-today-forum-share-your-voice/77884398007/', '["opinion"]', 'email', 'EXPECTED $0 — no fee shown', 'Статья — republication Gannett, проверить актуальность адреса', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('npr-health-freelance-guide-pitch', 'npr-health-freelance-guide', 'NPR Health freelance guide', 'https://healthjournalism.org/freelancers/freelance-market-guide/npr-freelance-market-guide/', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Только health angle, freelance-формат; гайд сторонний — подтвердить на NPR', 'third_party', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('tampa-bay-times-submit-a-letter-opinion', 'tampa-bay-times', 'Tampa Bay Times — Submit a letter', 'https://tampabaytimes-tampa-bay-times.cdn.zephr.com/opinion/submit-letter/', '["opinion"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Только letters; не news tips', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('outside-pitch-contacts-news-tip-pitch', 'outside', 'Outside — pitch contacts', 'https://www.outsideonline.com/magazine/contact-us/how-to-pitch-freelance-outside-magazine/?scope=anon', '["news_tip", "pitch"]', 'email', 'EXPECTED $0 — no fee shown', 'Freelance/editorial bar высокий', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('chronicle-of-philanthropy-opinion-pitch-opinion', 'chronicle-of-philanthropy', 'Chronicle of Philanthropy — Opinion', 'https://www.philanthropy.com/how-to-submit-an-opinion-piece/', '["pitch", "opinion"]', 'email', 'EXPECTED $0 — no fee shown', 'Exclusivity required для opinion', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('nonprofit-quarterly-submissions-press-release-pitch', 'nonprofit-quarterly', 'Nonprofit Quarterly — Submissions', 'https://nonprofitquarterly.org/submissions/', '["press_release", "pitch"]', 'email', 'VERIFIED $0 (pitch бесплатен; NPQ платит авторам $300/$500)', 'No press releases, no self-promotion; оригинал + эксклюзивность', 'opened', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('next-avenue-pbs-50-audience-pitch', 'next-avenue-pbs-50-audience', 'Next Avenue (PBS 50+ audience)', 'https://healthjournalism.org/freelancers/freelance-market-guide/next-avenue-freelance-market-guide/', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', '50+ аудитория; гайд сторонний', 'third_party', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('beacon-senior-news-write-for-us-pitch', 'beacon-senior-news', 'Beacon Senior News — Write for Us', 'https://coloradosprings.beaconseniornews.com/pages/write', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Регион Colorado Springs–Pueblo; только для релевантных историй', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('run247-news-interviews-pitch', 'run247', 'RUN247 — News & Interviews', 'https://run247.com/work-with-us', '["pitch"]', 'email', 'EXPECTED $0 — no fee shown', 'Off-road/trail фокус; news team не берёт gear/nutrition/commercial', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('runner-s-world-news-tips-news-tip-pitch', 'runner-s-world', 'Runner''s World — News tips', NULL, '["news_tip", "pitch"]', 'email', 'UNKNOWN', 'НЕ использовать без подтверждения на hearst.com', 'third_party', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('sports-page-ideas-pitch', 'sports-page', 'Sports Page — ideas', 'https://github.com/pem725/the-sports-page/blob/HEAD/tracking/contributor-pipeline.md', '["pitch"]', 'email', 'UNKNOWN', 'Только идеи с числом в центре; источник — чужой workflow, не официальный сайт издания', 'third_party', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('the-outdoor-journal-contribute-pitch', 'the-outdoor-journal', 'The Outdoor Journal — Contribute', 'https://www.outdoorjournal.com/contribute/', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Outdoor фокус', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('running-usa-editorial-pitch', 'running-usa', 'Running USA — editorial', 'https://www.runningusa.org/about-us/running-usa-about/', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Press-release distribution — только member benefit (не бесплатно без членства)', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('usa-running-races-listings-event', 'usa-running-races', 'USA Running Races — listings', 'https://usarunningraces.com/wp-content/uploads/USARunningRacesMediaKit.pdf', '["event"]', 'web_form', 'VERIFIED $0 (Standard Listing)', 'Premium — платный', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('ahotu-event-listings-pitch', 'ahotu', 'AHOTU — event listings', 'https://www.worldssportsgroup.com/news/ahotu-expands-coverage', '["pitch"]', 'web_form', 'EXPECTED $0', 'Календарь включает walking/Nordic walking; релевантен', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('inside-philanthropy-news-press-release', 'inside-philanthropy', 'Inside Philanthropy — News', 'https://www.insidephilanthropy.com/about/contact', '["press_release"]', 'email', 'EXPECTED $0 — no fee shown', 'Philanthropy/nonprofit фокус', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('inside-philanthropy-guest-posts-guest-pitch-pitch', 'inside-philanthropy-2', 'Inside Philanthropy — Guest posts', 'https://www.insidephilanthropy.com/about/guest-post-guidelines', '["guest_pitch", "pitch"]', 'email', 'EXPECTED $0 — no fee shown', 'Только про конкретную nonprofit program обычно НЕ подходит — нужен sector angle', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('chronicle-newsroom-pitch', 'chronicle-newsroom', 'Chronicle newsroom', 'https://philanthropy.com/contact-us/', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Национальная значимость', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('nonprofit-quarterly-volunteer-newswire-w-pitch', 'nonprofit-quarterly-2', 'Nonprofit Quarterly — Volunteer newswire writers', 'https://nonprofitquarterly.org/join-the-npq-writers-cadre/', '["pitch"]', 'email', 'VERIFIED $0', 'Волонтёрская роль, требует регулярности', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('uf-news-submit-a-story-pitch', 'uf-news', 'UF News — Submit a Story', 'https://news.ufl.edu/submit-a-story/', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Только UF-connected work; события не продвигает', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('uf-at-work-submit-a-story-pitch', 'uf-at-work', 'UF at Work — Submit a Story', 'https://news.hr.ufl.edu/submit-a-story/', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Только UF faculty/staff', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('uf-phhp-submit-a-story-idea-pitch', 'uf-phhp', 'UF PHHP — Submit a Story Idea', 'https://phhp.ufl.edu/news-and-events/submit-a-story-idea/', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Нужна реальная UF connection', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('university-of-miami-news-contact-pitch', 'university-of-miami', 'University of Miami — News contact', 'https://news.miami.edu/contact/', '["pitch"]', 'email', 'EXPECTED $0 — no fee shown', 'Scope проверить; вероятно внутренняя', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('ucf-cecs-share-your-news-pitch', 'ucf-cecs', 'UCF CECS — Share Your News', 'https://www.cecs.ucf.edu/share-your-news/', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Только college-internal; ответ 5–7 business days', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('fsu-media-resources-pitch', 'fsu-media-resources', 'FSU Media Resources', 'https://news.fsu.edu/for-journalists/media-resources/', '["pitch"]', 'web_form', '—', 'Для журналистских запросов К FSU, не для внешних питчей — исключён как точка входа', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('miami-community-newspapers-event', 'miami-community-newspapers', 'Miami Community Newspapers', 'https://communitynewspapers.com', '["event"]', 'email', 'EXPECTED $0 — no fee shown', 'Только Miami-Dade', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('patch-neighbor-posts-events-press-release-event-', 'patch', 'Patch — Neighbor Posts / Events', 'https://patch.com', '["press_release", "event", "opinion", "pitch"]', 'email', 'EXPECTED $0 — no fee shown (featured promotion — платная, $1/день)', 'Нужна локальная привязка (real local); бизнесы — только featured', 'search_verified', 'Draft from the approved variant; a person sends it from the human-operated NWANA mailbox (president@/admin@); record sent_at and any reply in media_distributions. Never bulk-send.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('newsbreak-pitch', 'newsbreak', 'NewsBreak', NULL, '["pitch"]', 'web_form', '—', 'Официальный creator route не найден; сторонний PR про бесплатный Spotlight для small business — не подтверждён как nonprofit route. Исключён.', 'third_party', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('axios-tampa-bay-pitch', 'axios-tampa-bay', 'Axios Tampa Bay', NULL, '["pitch"]', 'web_form', '—', 'Newsletter существует, но официальный pitch/tip contact не найден. Гэп.', 'third_party', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('podcastguests-guest-match-service-guest-pitch', 'podcastguests', 'PodcastGuests — Guest Match Service', 'https://podcastguests.com/guest-match-service/', '["guest_pitch"]', 'web_form', 'VERIFIED $0 ("Sign up for free")', 'Ручной питч по каждому подкасту', 'opened', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('the-morning-shakeout-running-newsletter--pitch', 'the-morning-shakeout-running-newsletter-podcast', 'The Morning Shakeout (running newsletter + podcast)', 'https://themorningshakeout.com/about/', '["pitch"]', 'web_form', 'EXPECTED $0 — no fee shown', 'Weekly running audience', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('eventbrite-event', 'eventbrite', 'Eventbrite', 'https://www.eventbrite.com/organizer/pricing/', '["event"]', 'web_form', 'VERIFIED $0 — для событий без платных билетов', 'Для платных событий — ticketing fees; `VERIFIED $0` только для free-attendee events', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('allevents-event', 'allevents', 'AllEvents', 'https://allevents.in/pages/onboard', '["event"]', 'web_form', 'EXPECTED $0 ("free to get started")', '—', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('run-asheville-submit-event-pitch', 'run-asheville', 'Run Asheville — Submit Event', 'https://runasheville.com:443/submit-event/', '["pitch"]', 'web_form', 'VERIFIED $0', 'Только Western North Carolina', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('indy-week-cityspark-event', 'indy-week-cityspark', 'INDY Week / CitySpark', 'https://indyweek.com/wp-content/uploads/2025/11/How-to-Submit-an-Event-to-INDY-Calendar_CitySpark-Website.pdf', '["event"]', 'web_form', 'VERIFIED $0 (basic)', 'География North Carolina', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('prlog-submit-press-release', 'prlog', 'PRLog — submit', 'https://www.prlog.Org/pub/', '["press_release"]', 'web_form', 'VERIFIED $0 (большинство услуг бесплатны; paid package optional)', '—', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('prlog-free-account-submission-press-release', 'prlog-2', 'PRLog — free account/submission', 'http://www.prlog.org/submit-free-press-release.html', '["press_release"]', 'web_form', 'VERIFIED $0', 'Только через форму после логина', 'search_verified', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('haro-revival-pitch', 'haro-revival', 'HARO (revival)', NULL, '["pitch"]', 'web_form', 'EXPECTED $0 ("free for journalists and sources", из `https://blog.connectively.us/featured-acquires-help-a-reporter-out-haro/`)', 'URL не конструировать — найти официально', 'third_party', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('openpr-pr-com-pitch', 'openpr-pr-com', 'OpenPR / PR.com', NULL, '["pitch"]', 'web_form', '—', 'Только сторонние упоминания; без открытых official pricing/submission pages — не включать', 'third_party', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');
INSERT OR IGNORE INTO media_submission_endpoints (endpoint_id, outlet_id, name, url, accepts, path_type, cost_status, eligibility, verification_level, manual_last_mile, account_required, notes) VALUES ('circleacts-pitch', 'circleacts', 'CircleActs', NULL, '["pitch"]', 'web_form', '—', 'Не исследован — гэп', 'third_party', 'Open the form URL, complete required fields with the approved release text, submit, then record the confirmation/published URL in media_distributions.external_url.', 0, '');

INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('wfts-tv-tampa-bay-28-newsroom-newsroom-newstips-wf', 'wfts-tv-tampa-bay-28', 'WFTS-TV / Tampa Bay 28 — Newsroom newsroom', 'newsroom', 'NewsTips@wfts.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'opened', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('wfts-tv-tampa-bay-28-newsroom-newsroom-813-354-282', 'wfts-tv-tampa-bay-28', 'WFTS-TV / Tampa Bay 28 — Newsroom newsroom', 'assignment desk', NULL, '(813) 354-2828', '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'opened', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('central-florida-public-media-orlando-npr-member-ne', 'central-florida-public-media-orlando-npr-member', 'Central Florida Public Media (Orlando, NPR member) newsroom', 'newsroom', 'newsroom@cfpublic.org', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'opened', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('central-florida-public-media-orlando-npr-member-ne-2', 'central-florida-public-media-orlando-npr-member', 'Central Florida Public Media (Orlando, NPR member) newsroom', 'newsroom', 'tips@cfpublic.org', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'opened', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('central-florida-public-media-orlando-npr-member-ne-2-3', 'central-florida-public-media-orlando-npr-member', 'Central Florida Public Media (Orlando, NPR member) newsroom', 'assignment desk', NULL, '(407) 273-2300', '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'opened', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('news4jax-wjxt-jacksonville-newsroom-newstips-news4', 'news4jax-wjxt-jacksonville', 'News4JAX / WJXT (Jacksonville) newsroom', 'newsroom', 'newstips@news4jax.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('news4jax-wjxt-jacksonville-newsroom-sports-wjxt-co', 'news4jax-wjxt-jacksonville', 'News4JAX / WJXT (Jacksonville) newsroom', 'newsroom', 'sports@wjxt.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('news4jax-wjxt-jacksonville-newsroom-newstips-wjxt-', 'news4jax-wjxt-jacksonville', 'News4JAX / WJXT (Jacksonville) newsroom', 'newsroom', 'newstips@wjxt.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('news4jax-wjxt-jacksonville-newsroom-904-393-9844', 'news4jax-wjxt-jacksonville', 'News4JAX / WJXT (Jacksonville) newsroom', 'assignment desk', NULL, '(904) 393-9844', '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('wftv-9-investigates-orlando-newsroom-9investigates', 'wftv-9-investigates-orlando', 'WFTV 9 Investigates (Orlando) newsroom', 'newsroom', '9investigates@wftv.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('wftv-9-investigates-orlando-newsroom-407-822-5999', 'wftv-9-investigates-orlando', 'WFTV 9 Investigates (Orlando) newsroom', 'assignment desk', NULL, '(407) 822-5999', '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('wplg-local-10-miami-newsroom-share-local10-com', 'wplg-local-10-miami', 'WPLG Local 10 (Miami) newsroom', 'newsroom', 'Share@Local10.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('fox-35-orlando-wofl-newsroom-866-55-fox35', 'fox-35-orlando-wofl', 'FOX 35 Orlando (WOFL) newsroom', 'assignment desk', NULL, '866-55-FOX35', '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('florida-times-union-opinion-newsroom-letters-jacks', 'florida-times-union', 'Florida Times-Union — Opinion newsroom', 'newsroom', 'letters@jacksonville.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('usa-today-forum-opinion-newsroom-forum-usatoday-co', 'usa-today-forum-opinion', 'USA TODAY Forum (opinion) newsroom', 'newsroom', 'forum@usatoday.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('wplg-local-10-newsroom-share-local10-com', 'wplg-local-10', 'WPLG Local 10 newsroom', 'newsroom', 'Share@Local10.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('fox-35-orlando-newsroom-866-55-fox35', 'fox-35-orlando', 'FOX 35 Orlando newsroom', 'assignment desk', NULL, '866-55-FOX35', '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('central-florida-public-media-npr-newsroom-newsroom', 'central-florida-public-media-npr', 'Central Florida Public Media (NPR) newsroom', 'newsroom', 'newsroom@cfpublic.org', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'opened', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('central-florida-public-media-npr-newsroom-tips-cfp', 'central-florida-public-media-npr', 'Central Florida Public Media (NPR) newsroom', 'newsroom', 'tips@cfpublic.org', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'opened', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('florida-times-union-opinion-newsroom-letters-jacks-2', 'florida-times-union', 'Florida Times-Union — Opinion newsroom', 'newsroom', 'letters@jacksonville.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('usa-today-forum-newsroom-forum-usatoday-com', 'usa-today-forum', 'USA TODAY Forum newsroom', 'newsroom', 'forum@usatoday.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('outside-pitch-contacts-newsroom-newstips-outsidein', 'outside', 'Outside — pitch contacts newsroom', 'newsroom', 'newstips@outsideinc.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('outside-pitch-contacts-newsroom-features-outsidein', 'outside', 'Outside — pitch contacts newsroom', 'newsroom', 'features@outsideinc.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('outside-pitch-contacts-newsroom-adventure-outsidei', 'outside', 'Outside — pitch contacts newsroom', 'newsroom', 'adventure@outsideinc.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('chronicle-of-philanthropy-opinion-newsroom-opinion', 'chronicle-of-philanthropy', 'Chronicle of Philanthropy — Opinion newsroom', 'newsroom', 'opinions@philanthropy.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('chronicle-of-philanthropy-opinion-newsroom-letters', 'chronicle-of-philanthropy', 'Chronicle of Philanthropy — Opinion newsroom', 'newsroom', 'letters@philanthropy.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('nonprofit-quarterly-submissions-newsroom-submissio', 'nonprofit-quarterly', 'Nonprofit Quarterly — Submissions newsroom', 'newsroom', 'submissions@npqmag.org', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'opened', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('run247-news-interviews-newsroom-partners-247endura', 'run247', 'RUN247 — News & Interviews newsroom', 'newsroom', 'partners@247endurance.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('wjxt-news4jax-sports-desk-newsroom-sports-wjxt-com', 'wjxt-news4jax', 'WJXT News4JAX — Sports desk newsroom', 'newsroom', 'sports@wjxt.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('wjxt-news4jax-sports-desk-newsroom-newstips-wjxt-c', 'wjxt-news4jax', 'WJXT News4JAX — Sports desk newsroom', 'newsroom', 'newstips@wjxt.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('run247-news-interviews-newsroom-partners-247endura-2', 'run247', 'RUN247 — News & Interviews newsroom', 'newsroom', 'partners@247endurance.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('runner-s-world-news-tips-newsroom-hmdrwnews-hearst', 'runner-s-world', 'Runner''s World — News tips newsroom', 'newsroom', 'hmdrwnews@hearst.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'third_party', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('runner-s-world-news-tips-newsroom-hmdrwservice-hea', 'runner-s-world', 'Runner''s World — News tips newsroom', 'newsroom', 'hmdrwservice@hearst.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'third_party', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('sports-page-ideas-newsroom-ideas-thesportspage-net', 'sports-page', 'Sports Page — ideas newsroom', 'newsroom', 'ideas@thesportspage.net', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'third_party', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('outside-pitch-contacts-newsroom-newstips-outsidein-2', 'outside', 'Outside — pitch contacts newsroom', 'newsroom', 'newstips@outsideinc.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('outside-pitch-contacts-newsroom-features-outsidein-2', 'outside', 'Outside — pitch contacts newsroom', 'newsroom', 'features@outsideinc.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('outside-pitch-contacts-newsroom-adventure-outsidei-2', 'outside', 'Outside — pitch contacts newsroom', 'newsroom', 'adventure@outsideinc.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('run247-news-interviews-newsroom-partners-247endura-2-3', 'run247', 'RUN247 — News & Interviews newsroom', 'newsroom', 'partners@247endurance.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('inside-philanthropy-news-newsroom-editor-insidephi', 'inside-philanthropy', 'Inside Philanthropy — News newsroom', 'newsroom', 'editor@insidephilanthropy.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('inside-philanthropy-guest-posts-newsroom-philipr-i', 'inside-philanthropy-2', 'Inside Philanthropy — Guest posts newsroom', 'newsroom', 'philipr@insidephilanthropy.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('chronicle-of-philanthropy-opinion-newsroom-opinion-2', 'chronicle-of-philanthropy', 'Chronicle of Philanthropy — Opinion newsroom', 'newsroom', 'opinions@philanthropy.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('chronicle-of-philanthropy-opinion-newsroom-letters-2', 'chronicle-of-philanthropy', 'Chronicle of Philanthropy — Opinion newsroom', 'newsroom', 'letters@philanthropy.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('nonprofit-quarterly-submissions-newsroom-submissio-2', 'nonprofit-quarterly', 'Nonprofit Quarterly — Submissions newsroom', 'newsroom', 'submissions@npqmag.org', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'opened', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('nonprofit-quarterly-volunteer-newswire-writers-new', 'nonprofit-quarterly-2', 'Nonprofit Quarterly — Volunteer newswire writers newsroom', 'newsroom', 'vanessa@npqmag.org', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('university-of-miami-news-contact-newsroom-ummedia-', 'university-of-miami', 'University of Miami — News contact newsroom', 'newsroom', 'ummedia@miami.edu', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('miami-community-newspapers-newsroom-michael-commun', 'miami-community-newspapers', 'Miami Community Newspapers newsroom', 'newsroom', 'Michael@communitynewspapers.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('miami-community-newspapers-newsroom-grant-communit', 'miami-community-newspapers', 'Miami Community Newspapers newsroom', 'newsroom', 'Grant@communitynewspapers.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
INSERT OR IGNORE INTO media_contacts (contact_id, outlet_id, name, role, email, phone, beat, consent_class, source, verification_level, notes) VALUES ('patch-neighbor-posts-events-newsroom-contributors-', 'patch', 'Patch — Neighbor Posts / Events newsroom', 'newsroom', 'contributors@patch.com', NULL, '', 'RESEARCHED_COLD', 'catalog 2026-09-27', 'search_verified', 'Researched contact, no prior relationship. Individual targeted outreach only — never bulk via Email V2.');
