-- 0061: automatic news drafts
CREATE TABLE IF NOT EXISTS auto_news_settings (
	news_type TEXT PRIMARY KEY,
	auto_publish INTEGER NOT NULL DEFAULT 0,
	updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
INSERT OR IGNORE INTO auto_news_settings (news_type, auto_publish) VALUES
	('race_results', 0),
	('race_announcement_7d', 0),
	('race_announcement_1d', 0);

-- Markers on articles generated by the auto-news engine.
-- (SQLite: ADD COLUMN is idempotent-safe via the IF NOT EXISTS guard below
--  only on newer versions; we check with PRAGMA in application code instead.
--  These run once via the migration runner.)
