/**
 * Distribution evidence config for the orchestration layer.
 *
 * Authoritative source: migrations/0006-seed-core-distribution-rules.sql
 * (rule/action seed) and migrations/0013-add-series-hub-work-items.sql
 * (recorded purpose/deliverable/call-to-action metadata for the Series hub
 * actions). This file carries the config as committed; it does not invent
 * rules or actions. Production D1 was inspected on 2026-09-23 and holds
 * zero seeded rules/actions, so the orchestration reads this committed
 * config instead of pretending the D1 rows exist.
 */

export interface DistributionRuleConfig {
  rule_id: string;
  name: string;
  priority: number;
  match_object_type: string | null;
  match_program_family: string | null;
  match_commercial_role: string | null;
  match_capability_type: string | null;
  match_status: string | null;
}

export const DISTRIBUTION_RULES: readonly DistributionRuleConfig[] = [
  {
    rule_id: "RULE-OPEN-SERIES-HUB",
    name: "Open Series Hub Distribution",
    priority: 10,
    match_object_type: "COMPETITION-SERIES-HUB",
    match_program_family: "OPEN_SERIES",
    match_commercial_role: "SELLABLE",
    match_capability_type: "SPONSORSHIP",
    match_status: "active",
  },
  {
    rule_id: "RULE-OPEN-SERIES-DISTANCE",
    name: "Open Series Distance Distribution",
    priority: 20,
    match_object_type: "COMPETITION-DISTANCE-SERIES",
    match_program_family: "OPEN_SERIES",
    match_commercial_role: "SELLABLE",
    match_capability_type: "SPONSORSHIP",
    match_status: "active",
  },
  {
    rule_id: "RULE-OPEN-SERIES-EVENT",
    name: "Open Series Event Distribution",
    priority: 30,
    match_object_type: "COMPETITION-EVENT",
    match_program_family: "OPEN_SERIES",
    match_commercial_role: "PARTICIPATION",
    match_capability_type: "PARTICIPATION",
    match_status: "active",
  },
  {
    rule_id: "RULE-INSTRUCTOR-GROWTH-FUND",
    name: "Instructor Growth Fund Distribution",
    priority: 10,
    match_object_type: "FUNDRAISING-ASSET",
    match_program_family: "INSTRUCTOR_GROWTH_FUND",
    match_commercial_role: "SELLABLE",
    match_capability_type: "FUNDRAISING",
    match_status: "active",
  },
  {
    rule_id: "RULE-PARTNER-NETWORK",
    name: "Partner Network Distribution",
    priority: 20,
    match_object_type: "PARTNER-NETWORK",
    match_program_family: "PARTNER_NETWORK",
    match_commercial_role: "SELLABLE",
    match_capability_type: "SPONSORSHIP",
    match_status: "active",
  },
  {
    rule_id: "RULE-ATHLETE-ASSET",
    name: "Athlete Asset Distribution",
    priority: 20,
    match_object_type: "ATHLETE-ASSET",
    match_program_family: "ATHLETE_PROPERTY",
    match_commercial_role: "SELLABLE",
    match_capability_type: "SPONSORSHIP",
    match_status: "active",
  },
  {
    rule_id: "RULE-NWANA-SPORT",
    name: "NWANA Sport Distribution",
    priority: 20,
    match_object_type: "SPORT-ASSET",
    match_program_family: "NWANA_SPORT",
    match_commercial_role: "SELLABLE",
    match_capability_type: "SPONSORSHIP",
    match_status: "active",
  },
];

export interface DistributionActionConfig {
  action_id: string;
  rule_id: string;
  audience_id: string | null;
  action_type: string;
  channel: string;
  destination: string | null;
  execution_mode: string;
  priority: number;
  purpose: string | null;
  deliverable: string | null;
  call_to_action: string | null;
  content_scope: string | null;
}

export const DISTRIBUTION_ACTIONS: readonly DistributionActionConfig[] = [
  {
    action_id: "ACT-SERIES-HUB-FB",
    rule_id: "RULE-OPEN-SERIES-HUB",
    audience_id: "AUD-SERIES-HUB-PARTICIPANTS",
    action_type: "SOCIAL_POST",
    channel: "FACEBOOK",
    destination: "NWANA",
    execution_mode: "MANUAL_LAST_MILE",
    priority: 10,
    purpose: "Promote Series 2026 to Nordic walking participants on Facebook",
    deliverable: "Facebook post for the NWANA page",
    call_to_action: "Visit the Series hub and choose a distance",
    content_scope: "SERIES_PROMOTION",
  },
  {
    action_id: "ACT-SERIES-HUB-IG",
    rule_id: "RULE-OPEN-SERIES-HUB",
    audience_id: "AUD-SERIES-HUB-PARTICIPANTS",
    action_type: "SOCIAL_POST",
    channel: "INSTAGRAM",
    destination: "NWANA_OFFICIAL",
    execution_mode: "MANUAL_LAST_MILE",
    priority: 10,
    purpose: "Promote Series 2026 to Nordic walking participants on Instagram",
    deliverable: "Instagram post for NWANA Official",
    call_to_action: "Visit the Series hub and choose a distance",
    content_scope: "SERIES_PROMOTION",
  },
  {
    action_id: "ACT-SERIES-HUB-LINKEDIN",
    rule_id: "RULE-OPEN-SERIES-HUB",
    audience_id: "AUD-SERIES-HUB-PARTICIPANTS",
    action_type: "SOCIAL_POST",
    channel: "LINKEDIN",
    destination: "NWANA_PAGE",
    execution_mode: "APPROVAL_REQUIRED",
    priority: 20,
    purpose: "Present Series 2026 as a participation and organizational opportunity on LinkedIn",
    deliverable: "LinkedIn post for the NWANA page",
    call_to_action: "Visit the Series hub or contact NWANA",
    content_scope: "SERIES_PROMOTION",
  },
  {
    action_id: "ACT-SERIES-HUB-EMAIL",
    rule_id: "RULE-OPEN-SERIES-HUB",
    audience_id: "AUD-SERIES-HUB-PARTICIPANTS",
    action_type: "EMAIL_CAMPAIGN",
    channel: "RUNSIGNUP_EMAIL",
    destination: "SERIES_PARTICIPANTS",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: "Inform existing Series participants about the Series hub and the next participation opportunity",
    deliverable: "RunSignup email draft for Series participants",
    call_to_action: "Visit the Series hub and choose the next distance",
    content_scope: "PARTICIPANT_FOLLOW_UP",
  },
  {
    action_id: "ACT-SERIES-HUB-GOOGLE-ADS",
    rule_id: "RULE-OPEN-SERIES-HUB",
    audience_id: "AUD-SERIES-HUB-PARTICIPANTS",
    action_type: "GOOGLE_ADS_CAMPAIGN",
    channel: "GOOGLE_ADS_GRANT",
    destination: "OPEN_SERIES",
    execution_mode: "APPROVAL_REQUIRED",
    priority: 20,
    purpose: "Attract people searching for Nordic walking competitions to Series 2026",
    deliverable: "Google Ad Grant campaign draft",
    call_to_action: "Visit the Series hub and choose a distance",
    content_scope: "SERIES_ACQUISITION",
  },
  {
    action_id: "ACT-SERIES-HUB-SELLERS",
    rule_id: "RULE-OPEN-SERIES-HUB",
    audience_id: "AUD-SERIES-HUB-SPONSORS",
    action_type: "SELLER_OUTREACH",
    channel: "SELLER_NETWORK",
    destination: "NWANA_SELLERS",
    execution_mode: "NOT_CONNECTED",
    priority: 10,
    purpose: "Give NWANA sponsorship sellers a clear Series 2026 asset to present",
    deliverable: "Seller outreach brief for Series 2026",
    call_to_action: "Open a sponsorship conversation with NWANA",
    content_scope: "SPONSORSHIP_SALES",
  },
  {
    action_id: "ACT-SERIES-HUB-SEAT-THEORY",
    rule_id: "RULE-OPEN-SERIES-HUB",
    audience_id: "AUD-SERIES-HUB-SPONSORS",
    action_type: "SPONSORSHIP_MARKETPLACE",
    channel: "SEAT_THEORY",
    destination: "OPEN_SERIES",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: "Prepare Series 2026 for sponsorship marketplace visibility",
    deliverable: "Seat Theory listing draft",
    call_to_action: "Request a sponsor introduction or sponsorship conversation",
    content_scope: "SPONSORSHIP_MARKETPLACE",
  },
  {
    action_id: "ACT-SERIES-HUB-ZUBIE-FIVE",
    rule_id: "RULE-OPEN-SERIES-HUB",
    audience_id: "AUD-SERIES-HUB-SPONSORS",
    action_type: "SPONSORSHIP_MARKETPLACE",
    channel: "ZUBIE_FIVE",
    destination: "OPEN_SERIES",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: "Prepare Series 2026 for sponsorship marketplace visibility",
    deliverable: "Zubie Five listing draft",
    call_to_action: "Request a sponsor introduction or sponsorship conversation",
    content_scope: "SPONSORSHIP_MARKETPLACE",
  },
  {
    action_id: "ACT-SERIES-HUB-PRESS",
    rule_id: "RULE-OPEN-SERIES-HUB",
    audience_id: "AUD-SERIES-HUB-MEDIA",
    action_type: "PRESS_OUTREACH",
    channel: "MEDIA",
    destination: "SPORT_AND_HEALTH_MEDIA",
    execution_mode: "NOT_CONNECTED",
    priority: 30,
    purpose: "Pitch Series 2026 to sports and health media",
    deliverable: "Press pitch draft",
    call_to_action: "Cover Series 2026 or contact NWANA for information",
    content_scope: "MEDIA_OUTREACH",
  },
  {
    action_id: "ACT-SERIES-HUB-PARTNERS",
    rule_id: "RULE-OPEN-SERIES-HUB",
    audience_id: "AUD-SERIES-HUB-PARTNERS",
    action_type: "PARTNER_OUTREACH",
    channel: "PARTNER_NETWORK",
    destination: "SPORT_WELLNESS_EMPLOYER_COMMUNITY",
    execution_mode: "NOT_CONNECTED",
    priority: 30,
    purpose: "Invite sport, wellness, employer, and community partners to support or distribute Series 2026",
    deliverable: "Partner outreach brief",
    call_to_action: "Discuss partnership, audience distribution, hosting, or support",
    content_scope: "PARTNER_OUTREACH",
  },
  {
    action_id: "ACT-SERIES-DIST-FB",
    rule_id: "RULE-OPEN-SERIES-DISTANCE",
    audience_id: "AUD-SERIES-DIST-PARTICIPANTS",
    action_type: "SOCIAL_POST",
    channel: "FACEBOOK",
    destination: "NWANA",
    execution_mode: "MANUAL_LAST_MILE",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SERIES-DIST-IG",
    rule_id: "RULE-OPEN-SERIES-DISTANCE",
    audience_id: "AUD-SERIES-DIST-PARTICIPANTS",
    action_type: "SOCIAL_POST",
    channel: "INSTAGRAM",
    destination: "NWANA_OFFICIAL",
    execution_mode: "MANUAL_LAST_MILE",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SERIES-DIST-EMAIL",
    rule_id: "RULE-OPEN-SERIES-DISTANCE",
    audience_id: "AUD-SERIES-DIST-PARTICIPANTS",
    action_type: "EMAIL_CAMPAIGN",
    channel: "RUNSIGNUP_EMAIL",
    destination: "DISTANCE_SERIES_AUDIENCE",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SERIES-DIST-SELLERS",
    rule_id: "RULE-OPEN-SERIES-DISTANCE",
    audience_id: "AUD-SERIES-DIST-SPONSORS",
    action_type: "SELLER_OUTREACH",
    channel: "SELLER_NETWORK",
    destination: "NWANA_SELLERS",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SERIES-DIST-PRESS",
    rule_id: "RULE-OPEN-SERIES-DISTANCE",
    audience_id: "AUD-SERIES-DIST-MEDIA",
    action_type: "PRESS_OUTREACH",
    channel: "MEDIA",
    destination: "SPORT_MEDIA",
    execution_mode: "NOT_CONNECTED",
    priority: 30,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SERIES-EVENT-FB",
    rule_id: "RULE-OPEN-SERIES-EVENT",
    audience_id: "AUD-SERIES-EVENT-PARTICIPANTS",
    action_type: "SOCIAL_POST",
    channel: "FACEBOOK",
    destination: "NWANA",
    execution_mode: "MANUAL_LAST_MILE",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SERIES-EVENT-IG",
    rule_id: "RULE-OPEN-SERIES-EVENT",
    audience_id: "AUD-SERIES-EVENT-PARTICIPANTS",
    action_type: "SOCIAL_POST",
    channel: "INSTAGRAM",
    destination: "NWANA_OFFICIAL",
    execution_mode: "MANUAL_LAST_MILE",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SERIES-EVENT-EMAIL",
    rule_id: "RULE-OPEN-SERIES-EVENT",
    audience_id: "AUD-SERIES-EVENT-PARTICIPANTS",
    action_type: "EMAIL_CAMPAIGN",
    channel: "RUNSIGNUP_EMAIL",
    destination: "EVENT_AUDIENCE",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SERIES-EVENT-PRESS",
    rule_id: "RULE-OPEN-SERIES-EVENT",
    audience_id: "AUD-SERIES-EVENT-MEDIA",
    action_type: "PRESS_OUTREACH",
    channel: "MEDIA",
    destination: "LOCAL_AND_SPORT_MEDIA",
    execution_mode: "NOT_CONNECTED",
    priority: 30,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-FUND-DONOR-EMAIL",
    rule_id: "RULE-INSTRUCTOR-GROWTH-FUND",
    audience_id: "AUD-FUND-DONORS",
    action_type: "FUNDRAISING_OUTREACH",
    channel: "EMAIL",
    destination: "DONOR_AUDIENCE",
    execution_mode: "NOT_CONNECTED",
    priority: 10,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-FUND-FB",
    rule_id: "RULE-INSTRUCTOR-GROWTH-FUND",
    audience_id: "AUD-FUND-DONORS",
    action_type: "SOCIAL_POST",
    channel: "FACEBOOK",
    destination: "NWANA",
    execution_mode: "MANUAL_LAST_MILE",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-FUND-IG",
    rule_id: "RULE-INSTRUCTOR-GROWTH-FUND",
    audience_id: "AUD-FUND-DONORS",
    action_type: "SOCIAL_POST",
    channel: "INSTAGRAM",
    destination: "NWANA_OFFICIAL",
    execution_mode: "MANUAL_LAST_MILE",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-FUND-SELLERS",
    rule_id: "RULE-INSTRUCTOR-GROWTH-FUND",
    audience_id: "AUD-FUND-SPONSORS",
    action_type: "SELLER_OUTREACH",
    channel: "SELLER_NETWORK",
    destination: "NWANA_SELLERS",
    execution_mode: "NOT_CONNECTED",
    priority: 10,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-FUND-SEAT-THEORY",
    rule_id: "RULE-INSTRUCTOR-GROWTH-FUND",
    audience_id: "AUD-FUND-SPONSORS",
    action_type: "SPONSORSHIP_MARKETPLACE",
    channel: "SEAT_THEORY",
    destination: "INSTRUCTOR_GROWTH_FUND",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-FUND-ZUBIE-FIVE",
    rule_id: "RULE-INSTRUCTOR-GROWTH-FUND",
    audience_id: "AUD-FUND-SPONSORS",
    action_type: "SPONSORSHIP_MARKETPLACE",
    channel: "ZUBIE_FIVE",
    destination: "INSTRUCTOR_GROWTH_FUND",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-FUND-EMPLOYER-MATCH",
    rule_id: "RULE-INSTRUCTOR-GROWTH-FUND",
    audience_id: "AUD-FUND-EMPLOYERS",
    action_type: "CORPORATE_GIVING_OUTREACH",
    channel: "EMPLOYER_MATCHING",
    destination: "MATCHING_GIFT_EMPLOYERS",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-FUND-PRESS",
    rule_id: "RULE-INSTRUCTOR-GROWTH-FUND",
    audience_id: "AUD-FUND-MEDIA",
    action_type: "PRESS_OUTREACH",
    channel: "MEDIA",
    destination: "HEALTH_EDUCATION_NONPROFIT_MEDIA",
    execution_mode: "NOT_CONNECTED",
    priority: 30,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-PARTNER-OUTREACH",
    rule_id: "RULE-PARTNER-NETWORK",
    audience_id: "AUD-PARTNER-NETWORK-PARTNERS",
    action_type: "PARTNER_OUTREACH",
    channel: "PARTNER_NETWORK",
    destination: "ALL_PARTNER_TYPES",
    execution_mode: "NOT_CONNECTED",
    priority: 10,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-PARTNER-SPONSOR-SELLERS",
    rule_id: "RULE-PARTNER-NETWORK",
    audience_id: "AUD-PARTNER-NETWORK-SPONSORS",
    action_type: "SELLER_OUTREACH",
    channel: "SELLER_NETWORK",
    destination: "NWANA_SELLERS",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-PARTNER-PRESS",
    rule_id: "RULE-PARTNER-NETWORK",
    audience_id: "AUD-PARTNER-NETWORK-MEDIA",
    action_type: "PRESS_OUTREACH",
    channel: "MEDIA",
    destination: "BUSINESS_SPORT_NONPROFIT_MEDIA",
    execution_mode: "NOT_CONNECTED",
    priority: 30,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-ATHLETE-SELLERS",
    rule_id: "RULE-ATHLETE-ASSET",
    audience_id: "AUD-ATHLETE-SPONSORS",
    action_type: "SELLER_OUTREACH",
    channel: "SELLER_NETWORK",
    destination: "NWANA_SELLERS",
    execution_mode: "NOT_CONNECTED",
    priority: 10,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-ATHLETE-SEAT-THEORY",
    rule_id: "RULE-ATHLETE-ASSET",
    audience_id: "AUD-ATHLETE-SPONSORS",
    action_type: "SPONSORSHIP_MARKETPLACE",
    channel: "SEAT_THEORY",
    destination: "ATHLETE_ASSET",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-ATHLETE-ZUBIE-FIVE",
    rule_id: "RULE-ATHLETE-ASSET",
    audience_id: "AUD-ATHLETE-SPONSORS",
    action_type: "SPONSORSHIP_MARKETPLACE",
    channel: "ZUBIE_FIVE",
    destination: "ATHLETE_ASSET",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-ATHLETE-PRESS",
    rule_id: "RULE-ATHLETE-ASSET",
    audience_id: "AUD-ATHLETE-MEDIA",
    action_type: "PRESS_OUTREACH",
    channel: "MEDIA",
    destination: "SPORT_MEDIA",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-ATHLETE-PARTNERS",
    rule_id: "RULE-ATHLETE-ASSET",
    audience_id: "AUD-ATHLETE-SPORT-PARTNERS",
    action_type: "PARTNER_OUTREACH",
    channel: "PARTNER_NETWORK",
    destination: "SPORT_EQUIPMENT_MEDIA",
    execution_mode: "NOT_CONNECTED",
    priority: 30,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SPORT-SELLERS",
    rule_id: "RULE-NWANA-SPORT",
    audience_id: "AUD-SPORT-SPONSORS",
    action_type: "SELLER_OUTREACH",
    channel: "SELLER_NETWORK",
    destination: "NWANA_SELLERS",
    execution_mode: "NOT_CONNECTED",
    priority: 10,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SPORT-SEAT-THEORY",
    rule_id: "RULE-NWANA-SPORT",
    audience_id: "AUD-SPORT-SPONSORS",
    action_type: "SPONSORSHIP_MARKETPLACE",
    channel: "SEAT_THEORY",
    destination: "NWANA_SPORT",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SPORT-ZUBIE-FIVE",
    rule_id: "RULE-NWANA-SPORT",
    audience_id: "AUD-SPORT-SPONSORS",
    action_type: "SPONSORSHIP_MARKETPLACE",
    channel: "ZUBIE_FIVE",
    destination: "NWANA_SPORT",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SPORT-PRESS",
    rule_id: "RULE-NWANA-SPORT",
    audience_id: "AUD-SPORT-MEDIA",
    action_type: "PRESS_OUTREACH",
    channel: "MEDIA",
    destination: "SPORT_MEDIA",
    execution_mode: "NOT_CONNECTED",
    priority: 20,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
  {
    action_id: "ACT-SPORT-PARTNERS",
    rule_id: "RULE-NWANA-SPORT",
    audience_id: "AUD-SPORT-PARTNERS",
    action_type: "PARTNER_OUTREACH",
    channel: "PARTNER_NETWORK",
    destination: "SPORT_HEALTH_WELLNESS",
    execution_mode: "NOT_CONNECTED",
    priority: 30,
    purpose: null,
    deliverable: null,
    call_to_action: null,
    content_scope: null,
  },
];
